services:
    # database
    demo-db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: pokemon-db
        environment: 
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=OpalIsMyPuppy1!
        ports:
            # HOST : Container
            - "1433:1433"
        volumes:
            # 防止容器爆炸后数据丢失
            - mssql_data:/var/opt/mssql
    
    
    # TODO: add redis
    # our api
    demo-api:
        # search dockerfile in dir
        build: .
        container_name: pokemon-api
        ports:
            - "8080:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development  
            - ConnectionStrings__PokeMonCenterDB=Server=demo-db;Database=PokemonDb;User Id=sa;Password=OpalIsMyPuppy1!;TrustServerCertificate=True;
        depends_on:
            - demo-db

volumes:
    mssql_data: